from typing import Any
from awsglue.context import GlueContext

class Job:
    def __init__(self, glue_context: GlueContext) -> None: ...
    def init(self, job_name: str, args: dict[str, str]) -> None: ...
    def commit(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
